# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://theideasmith.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: The Thoughtforge
  avatar: logo.png
  gravatar: # Email MD5 hash
  description: "My school of thought" #used by search engines
  # Header and footer text
  header_text: >

   My goal and challenge is to intuitively understand the fundamental nature of complex things.

  header_text_feature_image: img/board.png
  footer_text: >
   Powered by <a hrefs"http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: aclscientist@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "theideasmith"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/akiva-lipshitz-1aa1b0121 # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  http://stackoverflow.com/users/3499258/theideasmith
  steam:
  tumblr:
  twitter: "theideasmith"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_r`ss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 9
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
